### ISSUE TITLE
Linebreaks are not imported

### ISSUE THREAD

**Issue by Alex-SBB** [SchweizerischeBundesbahnen/ch.sbb.polarion.extension.excel-importer#63]
### Current Behavior

Linebreaks / Newlines inside a single Excel cell are not imported into Polarion. In Polarion the text is a single line, even when the field is configured as rich text field.

![Import_Excel_To_Polarion](https://github.com/user-attachments/assets/b5ccb705-a9bf-4372-a905-22591d60a1e8)

### Expected Behavior

Import linebreaks as written in Excel.

### Steps To Reproduce

Import an Excel with linebreaks within single cell.

### Environment - OS

Windows

### Polarion version

2410

### Extension Version

2.8.2

**Comment by grigoriev** [comment]
@Alex-SBB we can not reproduce the issue. 
Could you please provide us with the test data? 
Are you sure that the target field is multiline text field, but not single line string field?
